### PR TITLE
z2mi-ar-iaas-ansible-pr

### PR DESCRIPTION
**Pull request by z2mi**

### CODE REVIEW

**Comment by z2mi** [comment]
hi, any news on reviewing this pr ?

**Comment by devrandom0** [comment]
Dear @z2mi ,
I'm going to test it. I will inform you ASAP.

**Comment by z2mi** [comment]
> Dear @z2mi ,
> I'm going to test it. I will inform you ASAP.

Dear @sinamoghaddas ,
Is there something that I can help you with ? 
I think I deserve a feedback after almost 3 months

**Comment by devrandom0** [comment]
Sorry, for being late, and hope you accept my apology.
it's working. 
I've tested it with this example:

```
ansible-inventory -i arvan.yml --graph
@all:
  |--@arvan:
  |  |--test-mnetwork
  |  |--test-windows-rescue
  |  |--ubuntu-g1-small2-su-1
  |  |--ubuntu-g1-small2-su-2
  |--@ungrouped:
```
and the `arvan.yml` is:
```
# ...
filter_by_dcs:
  - Herman
  - ir-thr-at1
```
How can I understand which VM for which DC (related to grouping)?

Also, It's not a bad idea to add some simple examples in the READMD.md with simple ad-hoc commands (such as ping, debug IP of VM, ...), add `ansible.cfg`

**Comment by z2mi** [comment]
> Sorry, for being late, and hope you accept my apology. it's working. I've tested it with this example:
> 
> ```
> ansible-inventory -i arvan.yml --graph
> @all:
>   |--@arvan:
>   |  |--test-mnetwork
>   |  |--test-windows-rescue
>   |  |--ubuntu-g1-small2-su-1
>   |  |--ubuntu-g1-small2-su-2
>   |--@ungrouped:
> ```
> 
> and the `arvan.yml` is:
> 
> ```
> # ...
> filter_by_dcs:
>   - Herman
>   - ir-thr-at1
> ```
> 
> How can I understand which VM for which DC (related to grouping)?
> 
> Also, It's not a bad idea to add some simple examples in the READMD.md with simple ad-hoc commands (such as ping, debug IP of VM, ...), add `ansible.cfg`

Tnx , I will add examples to README.md. 

You can create groups and categorize VMs into those groups  in two ways :
- Jinja conditionals : for example following will create group `amsterdam` and add VM to that if  city attribute of VM  is equal to  amsterdam
```
...
groups:
  amsterdam : 'city|lower == "amsterdam"'
```
- with keyed_groups : for example following  will add VMs in Herman DC into group `arvan_herman_amsterdam_netherlands` , VMs in  Shahriar DC into group `arvan_shahriar_tabriz_iran` , ...
```
...
keyed_groups:
  - prefix: arvan
    key: '[dc_name|lower, city|lower, country|lower]|join("_")'
    parent_group: arvan
```

Also you can find an example of all host variables returned by plugin  ( dc_name, city, country, ... ) in repo

btw `filter_by_dcs` won't create groups and just add VMs to inventory if they are in provided list of DCs ( other VMs won't show up in inventory)

**Comment by z2mi** [comment]
Dear @sinamoghaddas , 
I added examples to README.md, please let me know if any other changes are required.

**Comment by z2mi** [comment]
Dear @sinamoghaddas ,
Is there anything else that I can help you with ?

**Comment by devrandom0** [comment]
No, Good job. Thanks

cc: @smesgary

**Pull request merged**
